scrape_configs:
  - job_name: 'sm-adapters'

    # scrape targets each hour
    scrape_interval: 60m

    static_configs:
      - targets: ['192.168.1.2:9130']
        labels:
          group: 'youtube'
